/* Funções de agregação numéricas */

CREATE TABLE VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	JANEIRO FLOAT(10, 2),
	FEVEREIRO FLOAT(10, 2),
	MARCO FLOAT (10, 2)
);

INSERT INTO VENDEDOR VALUES(NULL, 'MARCOS', 'M', 121212.2, 23232.2, 23211.2);
INSERT INTO VENDEDOR VALUES(NULL, 'MARIA', 'F', 6565.2, 3432.2, 432222.2);
INSERT INTO VENDEDOR VALUES(NULL, 'CLAUDIA', 'F', 7575.2, 644646.2, 233.2);
INSERT INTO VENDEDOR VALUES(NULL, 'PIETRA', 'F', 5757.2, 5454.2, 3443.2);
INSERT INTO VENDEDOR VALUES(NULL, 'MARCIA', 'F', 6446.2, 2323.2, 232.2);
INSERT INTO VENDEDOR VALUES(NULL, 'HIGOR', 'M', 3535.2, 35.2, 3535.2);
INSERT INTO VENDEDOR VALUES(NULL, 'FELIPE', 'M', 3535.2, 535.2, 2323.2);
INSERT INTO VENDEDOR VALUES(NULL, 'CARLOS', 'M', 6453.2, 6434.2, 3535.2);
INSERT INTO VENDEDOR VALUES(NULL, 'ZÉ', 'M', 5454.2, 4545.2, 34545.2);
INSERT INTO VENDEDOR VALUES(NULL, 'JOÃO', 'M', 34342.2, 23232, 4.2);


/* MAX - Traz o maior valor da coluna */

SELECT MAX(JANEIRO) AS "MAIOR DE JANEIRO" FROM VENDEDOR;


/* MIN - Traz o menor valor da coluna */

SELECT MIN(JANEIRO) AS "MENOR DE JANEIRO" FROM VENDEDOR;

/* AVG - Traz o valor médio da coluna */

SELECT AVG(JANEIRO) AS "MÉDIA DE JANEIRO" FROM VENDEDOR;


-- Várias funções

SELECT MAX(JANEIRO) AS "MAX_JAN",
MIN(JANEIRO) AS "MIN_JAN",
AVG(JANEIRO) AS "MEDIA_JAN"
FROM VENDEDOR;


/* TRUNCATE */

SELECT MAX(JANEIRO) AS "MAX_JAN",
TRUNCATE(MIN(JANEIRO), 1) AS "MIN_JAN",
AVG(JANEIRO) AS "MEDIA_JAN"
FROM VENDEDOR;


/* Agregação com SUM */

SELECT SUM(JANEIRO) AS "SOMA_JANEIRO", 
SUM(FEVEREIRO) AS "SOMA_FEVEREIRO",
SUM(JANEIRO) AS "SOMA_MARÇO"
FROM VENDEDOR;


-- Vendas por sexo

SELECT SEXO, SUM(MARCO) AS "TOTAL_MARCO" FROM VENDEDOR
GROUP BY SEXO;
