/* Nome, Sexo, Bairro, Cidade, Tipo, Número */

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, 
TELEFONE.TIPO, TELEFONE.NUMERO FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = IDENDERECO
INNER JOIN TELEFONE
ON IDCLIENTE = IDTELEFONE;



SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO FROM CLIENTE C
INNER JOIN ENDERECO E 
ON IDCLIENTE = IDENDERECO
INNER JOIN TELEFONE T 
WHERE IDCLIENTE = IDTELEFONE;