/* 

MODELAGEM BÁSICA

ENTIDADE -> TABELA
CAMPOS OU REGISTROS -> ATRIBUTOS

CADASTRO DE CLIENTE

NOME - CARACTER(30
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

PROCESSOS DE MODELAGEM

MODELAGEM CONCEITUAL -> RASCUNHO
MODELAGEM LÓGICA -> QUALQUER PROGRAMA DE MODELAGEM
MODELAGEM FÍSICA -> SCRIPTS DE BANCO
*/

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA CLIENTES */

CREATE TABLE CLIENTES (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBRINDO A ESTRUTURA DA TABELA */

DESC NOME DA TABELA;


/* SINTAXE BÁSICA PARA INSERÇÃO DE VALORES */

INSERT INTO NOME DA TABELA...

/* FORMA 1 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES(
	'JOAO',
	'M',
	'JOAO@GMAIL.COM',
	'12345678',
	'233432323',
	'PIST DANCE - RIO DE JANEIRO'
);
	
	
INSERT INTO CLIENTE VALUES(
	'MARIA',
	'F',
	'MARIA@GMAIL.COM',
	'12345678',
	'1223232323'
	'DJ FARAÓ - RIO DE JANEIRO'
);
	
	
INSERT INTO CLIENTE VALUES(
	'PEDRO',
	'M',
	'PEDRO@GMAIL.COM',
	'12345678',
	'234565643'
);
	
	
/* FORMA 2 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES(
	'LILIAN',
	'F',
	'SENADOR SOARES - RJ',
	'2325434343',
	'233434232'
);


/* COMANDO SELECT */

SELECT NOME AS CLIENTE, SEXO EMAIL FROM CLIENTE;

SELECT * FROM CLIENTE;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;	

SELECT NOME, SEXO, EMAIL, NOW() AS DATA_HORA FROM CLIENTE;	


/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'F';


/* FILTRANDO COM O LIKE E UTILIZANDO O CORINGA % */

SELECT NOME, EMAIL FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, EMAIL FROM CLIENTE
WHERE ENDERECO LIKE 'RJ%';

SELECT NOME, EMAIL FROM CLIENTE
WHERE ENDERECO LIKE '%RJ%';

