/* Utilizando o order by */

CREATE TABLE ALUNOS(
	NUMERO INT,
	NOME VARCHAR(30)
);

INSERT INTO ALUNOS VALUES(1, 'HIGOR');
INSERT INTO ALUNOS VALUES(3, 'CARLOS');
INSERT INTO ALUNOS VALUES(4, 'PEDRO');
INSERT INTO ALUNOS VALUES(2, 'ANA');
INSERT INTO ALUNOS VALUES(6, 'MARIA');
INSERT INTO ALUNOS VALUES(6, 'CLARA');
INSERT INTO ALUNOS VALUES(3, 'JORGE');
INSERT INTO ALUNOS VALUES(10, 'PIETRA');
INSERT INTO ALUNOS VALUES(11, 'LARISSA');
INSERT INTO ALUNOS VALUES(0, 'VITOR');
INSERT INTO ALUNOS VALUES(3, 'ROSA');
INSERT INTO ALUNOS VALUES(9, 'CLAUDIA');
INSERT INTO ALUNOS VALUES(8, 'MURILO');
INSERT INTO ALUNOS VALUES(7, 'CARLOS');
INSERT INTO ALUNOS VALUES(6, 'LEONARDO');


SELECT * FROM ALUNOS
ORDER BY NUMERO;

SELECT * FROM ALUNOS
ORDER BY 1; -- Ordenando pelo índice da coluna

SELECT * FROM ALUNOS
ORDER BY 2;


/* Ordenando por mais de uma coluna */

SELECT * FROM ALUNOS
ORDER BY NUMERO, NOME;


/* Order by DESC / ASC (crescente e decrescente) */

SELECT * FROM ALUNOS
ORDER BY NUMERO ASC;

SELECT * FROM ALUNOS
ORDER BY NUMERO DESC;



SELECT 	C.NOME,
 		C.SEXO,
  		C.EMAIL,
   		T.TIPO,
    	T.NUMERO,
     	E.BAIRRO,
      	E.CIDADE,
       	E.ESTADO 
FROM CLIENTE C
INNER JOIN TELEFONE T  
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY 1;